name: CI

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    uses: dvsa/.github/.github/workflows/php-library-security.yml@main
    with:
      php-versions: "[\"8.2\", \"8.3\", \"8.4\", \"8.5\"]"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  static-analysis-8-2:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: "8.2"

  static-analysis-8-3:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: "8.3"

  static-analysis-8-4:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: "8.4"

  static-analysis-8-5:
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: "8.5"

  tests:
    uses: dvsa/.github/.github/workflows/php-library-tests.yml@main
    with:
      php-versions: "[\"8.2\", \"8.3\", \"8.4\", \"8.5\"]"
      fail-fast: false
