name: CI

on:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  security:
    env:
      COMPOSER_IGNORE_PLATFORM_REQS: 1
    uses: dvsa/.github/.github/workflows/php-library-security.yml@main
    with: 
      php-versions: "[\"8.3\"]"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  static-analysis:
    env:
      COMPOSER_IGNORE_PLATFORM_REQS: 1
    uses: dvsa/.github/.github/workflows/php-library-static.yml@main
    with:
      php-version: '8.3'

  tests:
    env:
      COMPOSER_IGNORE_PLATFORM_REQS: 1
    uses: dvsa/.github/.github/workflows/php-library-tests.yml@main
    with:
      php-versions: "[\"8.3\"]"
      fail-fast: false
